version: '3.1'

services:
  dathin-session:
    image: dathin-session:0.0.1-SNAPSHOT
    ports:
      - 9000:9000
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES: postgres
      REDIS: redis
    networks:
      - dathin-session
