version: '3.1'

services:
  postgres:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_PASSWORD: xDxDxDxD
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - dathin-session
  redis:
    image: redis:6.2.3
    restart: always
    networks:
      - dathin-session

volumes:
  postgres-volume:
    driver: local

networks:
  dathin-session: